import { supabase } from './supabase'
export async function fetchConnections(userId:string){if(!supabase)return{matches:[],blocks:[]};const[{data:matches,error},{data:blocks}]=await Promise.all([supabase.from('matches').select('*').or(`user_a.eq.${userId},user_b.eq.${userId}`).order('created_at',{ascending:false}),supabase.from('user_blocks').select('*').eq('blocker_id',userId)]);if(error)throw error;const ids=[...(matches??[]).map(x=>x.user_a===userId?x.user_b:x.user_a),...(blocks??[]).map(x=>x.blocked_id)];const{data:profiles}=ids.length?await supabase.from('profiles').select('*').in('id',[...new Set(ids)]):{data:[]};return{matches:(matches??[]).map(x=>({...x,partner:profiles?.find(p=>p.id===(x.user_a===userId?x.user_b:x.user_a))})),blocks:(blocks??[]).map(x=>({...x,profile:profiles?.find(p=>p.id===x.blocked_id)}))}}
export async function endMatch(id:string){if(!supabase)throw new Error('Supabase 尚未配置');const{error}=await supabase.rpc('end_match',{target_match:id});if(error)throw error}
export async function unblockUser(userId:string,target:string){if(!supabase)throw new Error('Supabase 尚未配置');const{error}=await supabase.from('user_blocks').delete().eq('blocker_id',userId).eq('blocked_id',target);if(error)throw error}
export async function submitVerification(userId:string,type:string,organization:string,email:string,file?:File){if(!supabase)throw new Error('Supabase 尚未配置');let evidence_url:null|string=null;if(file){if(file.size>8*1024*1024)throw new Error('证明材料不能超过 8 MB');if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw new Error('仅支持 JPG、PNG、WebP 或 PDF');const ext=file.name.split('.').pop()||'jpg',path=`${userId}/${crypto.randomUUID()}.${ext}`;const{error}=await supabase.storage.from('verification-evidence').upload(path,file,{contentType:file.type});if(error)throw error;evidence_url=path}const{error}=await supabase.from('verification_requests').insert({user_id:userId,verification_type:type,organization,contact_email:email,evidence_url});if(error)throw error}
export async function fetchAdminQueue(){if(!supabase)return{verifications:[],reports:[]};const[{data:verifications,error},{data:reports}]=await Promise.all([supabase.from('verification_requests').select('*').order('created_at',{ascending:false}),supabase.from('reports').select('*').order('created_at',{ascending:false})]);if(error)throw error;return{verifications:verifications??[],reports:reports??[]}}
export async function getEvidenceUrl(path:string){if(!supabase)throw new Error('Supabase 尚未配置');const{data,error}=await supabase.storage.from('verification-evidence').createSignedUrl(path,300);if(error)throw error;return data.signedUrl}
export async function moderateTarget(userId:string|null,postId:string|null,action:string,reason:string,hours?:number){if(!supabase)throw new Error('Supabase 尚未配置');const{error}=await supabase.rpc('moderate_target',{target_user:userId,target_post:postId,chosen_action:action,action_reason:reason,duration_hours:hours});if(error)throw error}
export async function resolveReport(id:string,resolution:'resolved'|'dismissed'){if(!supabase)throw new Error('Supabase 尚未配置');const{error}=await supabase.rpc('resolve_report',{report_id:id,resolution});if(error)throw error}
export async function adminSearchUsers(query=''){if(!supabase)return[];const{data,error}=await supabase.rpc('admin_search_users',{search_text:query,result_limit:50});if(error)throw error;return data??[]}
export async function exportMyData(){if(!supabase)throw new Error('Supabase 尚未配置');const{data,error}=await supabase.rpc('export_my_data');if(error)throw error;return data}
export async function deleteMyAccount(){if(!supabase)throw new Error('Supabase 尚未配置');const{error}=await supabase.rpc('delete_my_account',{confirm_text:'DELETE MY ACCOUNT'});if(error)throw error}
export async function reviewVerification(id:string,decision:'approved'|'rejected',note=''){if(!supabase)throw new Error('Supabase 尚未配置');const{error}=await supabase.rpc('review_verification',{request_id:id,decision,note});if(error)throw error}
