import { useState, Suspense, lazy } from 'react'
import { motion } from 'framer-motion'
import { ArrowRight, BookOpen, Camera, Coffee, LoaderCircle, MapPin, Settings, ShieldCheck, User } from 'lucide-react'
import { useApp } from '../context/AppContext'
import Avatar from '../components/common/Avatar'
import PageLoading from '../components/common/PageLoading'

const ProfileEditor = lazy(() => import('../components/ProfileEditor'))

export default function Profile() {
  const { session, notify, posts, profile, userAvatar, syncProfileAndMatches, setShowAuth } = useApp()
  const [showProfileEditor, setShowProfileEditor] = useState(false)
  const ownPosts=session?posts.filter(post=>'authorId'in post&&post.authorId===session.user.id):[]
  const profileChecks=profile?[profile.avatar_url,profile.nickname,profile.school,profile.major,profile.city,profile.bio,profile.birth_year,profile.gender,profile.personality,profile.interests.length,profile.relationship_values.length,profile.ideal_date]:[]
  const profileCompletion=profile?Math.round(profileChecks.filter(Boolean).length/profileChecks.length*100):0
  const missingProfile=Math.ceil((100-profileCompletion)/Math.max(1,Math.round(100/profileChecks.length)))
  return <><motion.div className="page" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>{!session?<div className="assessment-locked"><User/><h2>登录后查看真实个人空间</h2><p>你的资料、照片和动态只会在登录后加载。</p><button className="primary" onClick={()=>setShowAuth(true)}>登录同频 <ArrowRight/></button></div>:!profile?<PageLoading label="正在加载真实资料"/>:<><section className="profile-hero glass-card"><div className="profile-cover"/><div className="profile-info"><button className="profile-avatar avatar-edit-entry" aria-label="编辑头像" onClick={()=>setShowProfileEditor(true)}><Avatar src={userAvatar} size={104}/><span><Camera size={16}/></span></button><div><h2>{profile.nickname}{profile.verified&&<ShieldCheck size={19}/>}</h2><p>{[profile.school,profile.major,profile.grade].filter(Boolean).join(' · ')||'尚未填写学习或工作信息'}</p><div className="tag-row">{[profile.personality,...profile.interests].filter(Boolean).slice(0,5).map(tag=><span key={tag}>{tag}</span>)}{!profile.personality&&!profile.interests.length&&<small>暂未添加兴趣标签</small>}</div></div><button className="secondary" onClick={()=>setShowProfileEditor(true)}><Settings size={17}/>编辑资料</button></div></section><div className="profile-layout"><section><div className="about-card glass-card"><h3>关于我</h3><p>{profile.bio||'还没有填写自我介绍，分享真实的你会让匹配更准确。'}</p><div className="details">{(profile.hometown||profile.city)&&<span><MapPin/>{profile.hometown?`来自${profile.hometown}`:''}{profile.hometown&&profile.city?'，':''}{profile.city?`现居${profile.city}`:''}</span>}{profile.life_stage&&<span><BookOpen/>{profile.life_stage}{profile.occupation?` · ${profile.occupation}`:''}</span>}{profile.ideal_date&&<span><Coffee/>理想约会：{profile.ideal_date}</span>}</div></div><div className="about-card glass-card"><h3>我的动态 <small>{ownPosts.length}</small></h3>{ownPosts.some(post=>post.image)?<div className="photo-grid">{ownPosts.filter(post=>post.image).slice(0,6).map(post=><img key={post.id} src={post.image} alt="我的动态"/>)}</div>:<div className="profile-empty">还没有发布带图片的动态</div>}</div></section><aside><div className="completion-card"><div className="circle-progress"><span>{profileCompletion}<small>%</small></span></div><h3>画像完成度</h3><p>{profileCompletion===100?'资料已完整，继续保持真实表达':`还有约 ${missingProfile} 项资料可以完善`}</p><button className="primary" onClick={()=>setShowProfileEditor(true)}>继续完善</button></div><div className="rail-card stat-card"><h3>我的内容</h3><div><span><b>{ownPosts.length}</b>真实动态</span><span><b>{ownPosts.reduce((sum,post)=>sum+post.likes,0)}</b>动态获赞</span><span><b>{profile.interests.length}</b>兴趣标签</span></div></div></aside></div></>}</motion.div>{showProfileEditor && session && <Suspense fallback={<div className="modal-backdrop"><LoaderCircle className="spin" /></div>}><ProfileEditor user={session.user} onClose={() => setShowProfileEditor(false)} onSaved={() => { void syncProfileAndMatches(session.user.id); notify('资料已更新') }} /></Suspense>}</>
}
