import { useCallback, useEffect, useRef, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Ban, Check, Heart, LoaderCircle, ShieldCheck, Unlink, Upload } from 'lucide-react'
import { endMatch, fetchConnections, submitVerification, unblockUser } from '../lib/account'

type Data=Awaited<ReturnType<typeof fetchConnections>>
const fallback='https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150'
export default function AccountCenter({session,isAdmin,onAdmin}:{session:Session|null;isAdmin:boolean;onAdmin:()=>void}){
 const[data,setData]=useState<Data>({matches:[],blocks:[]}),[tab,setTab]=useState<'matches'|'blocks'|'verify'>('matches'),[loading,setLoading]=useState(false),[message,setMessage]=useState('');const[type,setType]=useState('identity'),[organization,setOrganization]=useState(''),[email,setEmail]=useState(session?.user.email??''),file=useRef<HTMLInputElement>(null)
 const load=useCallback(async()=>{if(!session)return;setLoading(true);try{setData(await fetchConnections(session.user.id))}finally{setLoading(false)}},[session]);useEffect(()=>{window.setTimeout(()=>void load(),0)},[load])
 if(!session)return null
 const submit=async()=>{setLoading(true);try{await submitVerification(session.user.id,type,organization,email,file.current?.files?.[0]);setMessage('认证申请已提交，请等待审核')}catch(e){setMessage(e instanceof Error?e.message:'提交失败')}finally{setLoading(false)}}
 return <div className="account-center"><div className="account-tabs"><button className={tab==='matches'?'active':''} onClick={()=>setTab('matches')}><Heart/>配对管理</button><button className={tab==='blocks'?'active':''} onClick={()=>setTab('blocks')}><Ban/>屏蔽管理</button><button className={tab==='verify'?'active':''} onClick={()=>setTab('verify')}><ShieldCheck/>身份认证</button>{isAdmin&&<button onClick={onAdmin}><ShieldCheck/>审核后台</button>}</div>{loading&&<div className="account-loading"><LoaderCircle className="spin"/></div>}{tab==='matches'&&<div className="manage-card"><h2>我的配对</h2><p>管理已经建立的连接；解除后双方将无法继续发送消息。</p>{!data.matches.length?<div className="manage-empty">暂无配对记录</div>:data.matches.map(x=><div className="manage-row" key={x.id}><img src={x.partner?.avatar_url??fallback}/><div><b>{x.partner?.nickname??'同频用户'}</b><span>{x.partner?.life_stage} · {x.partner?.city??x.partner?.school}</span></div><em className={x.active?'active':''}>{x.active?'连接中':'已解除'}</em>{x.active&&<button onClick={async()=>{await endMatch(x.id);void load()}}><Unlink/>解除配对</button>}</div>)}</div>}{tab==='blocks'&&<div className="manage-card"><h2>屏蔽列表</h2><p>被屏蔽的人无法出现在你的推荐中，也无法与你建立联系。</p>{!data.blocks.length?<div className="manage-empty">屏蔽列表为空</div>:data.blocks.map(x=><div className="manage-row" key={x.blocked_id}><img src={x.profile?.avatar_url??fallback}/><div><b>{x.profile?.nickname??'已屏蔽用户'}</b><span>{x.profile?.city??x.profile?.school}</span></div><button onClick={async()=>{await unblockUser(session.user.id,x.blocked_id);void load()}}>恢复显示</button></div>)}</div>}{tab==='verify'&&<div className="manage-card verification-form"><h2>身份认证</h2><p>我们支持学校、工作单位和基础身份三种认证。材料仅供审核，不会公开展示。</p><label>认证类型<select value={type} onChange={e=>setType(e.target.value)}><option value="identity">身份认证</option><option value="school">学校认证</option><option value="work">职业认证</option></select></label><label>学校 / 公司 / 组织<input value={organization} onChange={e=>setOrganization(e.target.value)}/></label><label>联系邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="evidence"><Upload/><span>上传证明材料<small>JPEG、PNG、WebP 或 PDF，最大 5 MB</small></span><input ref={file} type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/></label>{message&&<div className="verify-message"><Check/>{message}</div>}<button className="primary" disabled={loading||!organization||!email} onClick={submit}>提交认证申请</button></div>}</div>
}
