import { useEffect, useMemo, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { ArrowLeft, ArrowRight, Brain, Check, Compass, Heart, LoaderCircle, RotateCcw, Sparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import { fetchProfileBundle } from '../lib/profiles'
import { saveAssessment, type Assessment } from '../lib/assessment'

const questions=[
 ['聚会结束后，你通常更想','继续和大家聊天','独处恢复精力','E','I'],['面对陌生环境，你更常','主动认识新朋友','先观察再慢慢融入','E','I'],['表达想法时，你倾向','边说边整理思路','想清楚后再表达','E','I'],['周末安排更吸引你的是','多人活动与新体验','安静空间与深度兴趣','E','I'],
 ['理解一件事时，你更相信','具体事实和亲身经验','整体趋势和潜在可能','S','N'],['聊天中你更容易注意','细节是否准确','观点背后的意义','S','N'],['学习新技能时你偏好','按步骤练习','先理解原理再探索','S','N'],['描述未来时你更常谈','可执行的现实计划','各种可能的生活图景','S','N'],
 ['发生分歧时你更看重','逻辑一致和公平标准','彼此感受和关系影响','T','F'],['朋友遇到困难时你通常先','分析问题和解决方法','理解情绪并给予陪伴','T','F'],['做重要决定时你更依赖','利弊和客观依据','内心价值和人的需要','T','F'],['接受反馈时你更欣赏','直接清楚指出问题','照顾感受地提出建议','T','F'],
 ['旅行前你更喜欢','提前规划关键安排','保留空间随机探索','J','P'],['面对截止日期你通常','提前推进获得确定感','临近时集中完成','J','P'],['日常生活让你更舒服的是','秩序清楚可以预期','灵活开放随时调整','J','P'],['计划临时改变时你通常','需要一点时间重新安排','很快接受并顺势而为','J','P'],
] as const
const values=['真诚','有边界感','情绪稳定','热爱生活','有行动力','幽默','温柔','保持好奇']
const styles=['规律计划','随性自由','安静独处','热闹社交','稳定陪伴','持续成长']
const descriptions:Record<string,{name:string;summary:string;strengths:string[];relationship:string;growth:string}>={
 INTJ:{name:'建筑师',summary:'独立、长远且重视内在逻辑，倾向用深度理解建立连接。',strengths:['有长期视角','重视真实与能力','关系中较为专注'],relationship:'适合尊重独处、愿意深度交流且边界清晰的关系。',growth:'尝试更及时表达感受，不让关心只停留在行动里。'},
 INTP:{name:'逻辑学家',summary:'好奇、开放且喜欢理解复杂系统，重视思想上的自由。',strengths:['善于分析','保持开放','尊重差异'],relationship:'适合能分享观点、允许彼此探索空间的关系。',growth:'重要感受可以直接说出来，不必等到完全想清楚。'},
 ENTJ:{name:'指挥官',summary:'目标明确、行动果断，习惯推动事情向更好的方向发展。',strengths:['执行力强','坦率可靠','善于共同成长'],relationship:'适合独立、有目标且能直接沟通的伙伴。',growth:'解决问题前先确认对方此刻需要方案还是陪伴。'},
 ENTP:{name:'辩论家',summary:'充满点子、喜欢探索新可能，在交流中获得灵感。',strengths:['创造力强','幽默灵活','乐于尝试'],relationship:'适合保持好奇、能坦诚讨论且不惧变化的关系。',growth:'稳定兑现小承诺，会让新鲜感沉淀成安全感。'},
 INFJ:{name:'提倡者',summary:'敏锐、理想且重视意义，期待被真正理解的深度关系。',strengths:['共情细腻','忠于价值','善于倾听'],relationship:'适合真诚、稳定并愿意讨论内心世界的关系。',growth:'不要让体谅替代边界，也允许自己提出具体需要。'},
 INFP:{name:'调停者',summary:'温柔、真诚且重视内心价值，希望关系保留真实与想象。',strengths:['真诚包容','情感丰富','重视独特性'],relationship:'适合温和、有边界并尊重个人节奏的伙伴。',growth:'理想之外，也用清晰行动确认彼此期待。'},
 ENFJ:{name:'主人公',summary:'热情、体贴且善于鼓励他人，重视关系中的共同成长。',strengths:['善于表达关心','有感染力','重视承诺'],relationship:'适合愿意回应、欣赏沟通并支持彼此目标的关系。',growth:'照顾别人时也要留意自己的能量和真实意愿。'},
 ENFP:{name:'竞选者',summary:'热情、自由且充满可能性，容易被真诚与独特吸引。',strengths:['情感开放','富有创意','带来活力'],relationship:'适合坦诚、有回应且能共同探索生活的伙伴。',growth:'把重要期待落到具体约定，减少热情后的不确定。'},
 ISTJ:{name:'物流师',summary:'可靠、细致且重视责任，通过稳定行动表达在乎。',strengths:['信守承诺','务实可靠','重视秩序'],relationship:'适合坦诚、稳定并尊重计划与边界的关系。',growth:'除了完成责任，也主动说出欣赏与柔软感受。'},
 ISFJ:{name:'守卫者',summary:'温和、细致且关注实际需要，擅长营造稳定和安心。',strengths:['体贴可靠','记得细节','重视陪伴'],relationship:'适合懂得回应、珍惜付出并愿意沟通需要的伙伴。',growth:'拒绝并不等于伤害关系，边界会让付出更可持续。'},
 ESTJ:{name:'总经理',summary:'直接、负责且注重执行，希望共同生活清楚而可靠。',strengths:['组织能力强','责任感高','沟通明确'],relationship:'适合务实、守信且愿意共同制定计划的伙伴。',growth:'计划之外给差异留空间，感受不总需要被立刻修正。'},
 ESFJ:{name:'执政官',summary:'友善、投入且重视互动，擅长让关系拥有温度和归属。',strengths:['善于照顾','表达积极','重视共同体验'],relationship:'适合愿意回应、重视仪式感并坦诚沟通的伙伴。',growth:'不必用所有人的认可判断自己的关系是否足够好。'},
 ISTP:{name:'鉴赏家',summary:'冷静、独立且善于解决实际问题，喜欢自然不黏腻的连接。',strengths:['临场冷静','尊重空间','行动务实'],relationship:'适合独立、直接且不过度控制彼此节奏的关系。',growth:'别让沉默承担全部表达，关键时刻说明你的在乎。'},
 ISFP:{name:'探险家',summary:'敏感、自在且重视当下体验，用行动和审美表达情感。',strengths:['温柔真实','感受细腻','尊重个体'],relationship:'适合温和、开放并尊重当下感受的伙伴。',growth:'面对长期问题时，清晰计划能保护你珍惜的自由。'},
 ESTP:{name:'企业家',summary:'直接、敏捷且热爱体验，喜欢在共同经历中建立默契。',strengths:['行动迅速','轻松坦率','适应力强'],relationship:'适合开放、独立并愿意一起体验生活的伙伴。',growth:'刺激之外，为对方提供可预期的回应与承诺。'},
 ESFP:{name:'表演者',summary:'热情、亲切且关注当下，善于让关系充满鲜活感。',strengths:['表达自然','善于陪伴','乐观有活力'],relationship:'适合真诚、有回应并愿意共享生活乐趣的伙伴。',growth:'遇到冲突时别急着绕开，温和面对会带来更深连接。'},
}
export default function AssessmentCenter({session,onSaved}:{session:Session;onSaved:()=>void}){
 const[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[choices,setChoices]=useState<Record<number,0|1>>({}),[result,setResult]=useState<string>('')
 const[answers,setAnswers]=useState<Assessment['answers']>({personality:'探索型',values:[],lifestyle:[],communication:'先倾听再表达',intent:'认真了解'})
 const[requirements,setRequirements]=useState<Assessment['requirements']>({personality:'',values:[],lifestyle:[],interests:[],intent:'认真了解'})
 useEffect(()=>{void fetchProfileBundle(session.user.id).then(x=>{const stored=x.profile.self_assessment;if(stored&&typeof stored==='object'){const a=stored as Assessment['answers'];setAnswers(current=>({...current,...a}));if(typeof a.mbti==='string')setResult(a.mbti);if(a.mbti_choices&&typeof a.mbti_choices==='object')setChoices(a.mbti_choices as unknown as Record<number,0|1>)}const ideal=x.preference.ideal_requirements;if(ideal&&typeof ideal==='object')setRequirements(current=>({...current,...ideal as Assessment['requirements']}))}).catch(()=>undefined)},[session])
 const scores=useMemo(()=>{const s={E:0,I:0,S:0,N:0,T:0,F:0,J:0,P:0};questions.forEach((q,i)=>{const c=choices[i];if(c!==undefined){const key=(c===0?q[3]:q[4]) as keyof typeof s;s[key]++}});return s},[choices])
 const mbti=`${scores.E>=scores.I?'E':'I'}${scores.S>=scores.N?'S':'N'}${scores.T>=scores.F?'T':'F'}${scores.J>=scores.P?'J':'P'}`
 const complete=Object.keys(choices).length===questions.length
 const toggle=(target:'answers'|'requirements',key:string,value:string)=>{const setter=target==='answers'?setAnswers:setRequirements;setter(prev=>{const current=Array.isArray(prev[key])?prev[key] as string[]:[];return{...prev,[key]:current.includes(value)?current.filter(x=>x!==value):[...current,value]}})}
 const multi=(target:'answers'|'requirements',key:string,items:string[])=>{const state=target==='answers'?answers:requirements,current=Array.isArray(state[key])?state[key] as string[]:[];return <div className="assessment-chips">{items.map(item=><button type="button" aria-pressed={current.includes(item)} className={current.includes(item)?'selected':''} key={item} onClick={()=>toggle(target,key,item)}>{current.includes(item)&&<Check/>}{item}</button>)}</div>}
 const submit=async()=>{if(!complete)return;setBusy(true);setError('');try{const combined={...answers,personality:mbti,mbti,mbti_scores:scores,mbti_choices:choices,assessment_version:2};await saveAssessment({answers:combined,requirements,weights:{values:35,lifestyle:25,interests:20,communication:10,intent:10}});setAnswers(combined);setResult(mbti);setPage(6)}catch(e){setError(e instanceof Error?e.message:'保存评测失败')}finally{setBusy(false)}}
 const start=page*4,end=Math.min(start+4,questions.length),report=descriptions[result]??descriptions[mbti]
 return <motion.div className="assessment-page combined-assessment" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><header><span className="section-kicker"><Brain/>MBTI × RELATIONSHIP MAPPING</span><h1>认识你的能量方式，也看见关系需要。</h1><p>16道偏好题结合价值观、生活节奏和理想对象要求，生成一份用于自我理解与匹配解释的组合报告。</p><small>这不是医学或心理诊断，结果会随经历和情境变化。</small></header><div className="assessment-progress"><i style={{width:`${Math.min(100,(page/6)*100)}%`}}/><span>{page<4?`MBTI ${Object.keys(choices).length}/16`:page===4?'关系画像':page===5?'确认分析':'结果报告'}</span></div>
 {page<4&&<section className="assessment-card mbti-card"><div className="assessment-step"><span>0{page+1}</span><div><h2>选择更自然的你</h2><p>没有正确答案，请选择大多数真实情境下更接近你的描述。</p></div></div><div className="mbti-questions">{questions.slice(start,end).map((q,offset)=>{const index=start+offset;return <fieldset key={q[0]}><legend>{index+1}. {q[0]}</legend><div><button type="button" aria-pressed={choices[index]===0} className={choices[index]===0?'selected':''} onClick={()=>setChoices({...choices,[index]:0})}><span>A</span>{q[1]}</button><button type="button" aria-pressed={choices[index]===1} className={choices[index]===1?'selected':''} onClick={()=>setChoices({...choices,[index]:1})}><span>B</span>{q[2]}</button></div></fieldset>})}</div><footer><button className="secondary" disabled={page===0} onClick={()=>setPage(page-1)}><ArrowLeft/>上一组</button><button className="primary" disabled={questions.slice(start,end).some((_,i)=>choices[start+i]===undefined)} onClick={()=>setPage(page+1)}>下一组<ArrowRight/></button></footer></section>}
 {page===4&&<section className="assessment-card"><div className="assessment-step"><span>05</span><div><h2>你的关系内核</h2><p>选择你本人最看重的品质和更舒服的生活节奏。</p></div></div><h3>我看重的关系品质</h3>{multi('answers','values',values)}<h3>我的生活节奏</h3>{multi('answers','lifestyle',styles)}<label className="assessment-select">发生分歧时，我通常<select value={String(answers.communication??'先倾听再表达')} onChange={e=>setAnswers({...answers,communication:e.target.value})}><option>先倾听再表达</option><option>直接说明观点</option><option>需要独处后沟通</option><option>先安抚情绪</option></select></label><footer><button className="secondary" onClick={()=>setPage(3)}><ArrowLeft/>返回题目</button><button className="primary" disabled={!(answers.values as string[]).length||!(answers.lifestyle as string[]).length} onClick={()=>setPage(5)}>理想关系<ArrowRight/></button></footer></section>}
 {page===5&&<section className="assessment-card"><div className="assessment-step"><span>06</span><div><h2>你期待怎样的彼此</h2><p>这些要求将与MBTI倾向共同用于推荐解释，不会把类型当作硬性筛选。</p></div></div><h3>期待对方拥有的品质</h3>{multi('requirements','values',values)}<h3>期待共同的生活方式</h3>{multi('requirements','lifestyle',styles)}<label className="assessment-select">关系方向<select value={String(requirements.intent??'认真了解')} onChange={e=>setRequirements({...requirements,intent:e.target.value})}><option>认真了解</option><option>长期关系</option><option>从朋友开始</option><option>顺其自然</option></select></label>{error&&<div className="verify-message error">{error}</div>}<footer><button className="secondary" onClick={()=>setPage(4)}><ArrowLeft/>返回</button><button className="primary" disabled={busy||!(requirements.values as string[]).length} onClick={()=>void submit()}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}生成组合报告</button></footer></section>}
 {page===6&&report&&<section className="assessment-result"><div className="result-hero"><span><Sparkles/>你的组合画像</span><strong>{result}</strong><h2>{report.name}</h2><p>{report.summary}</p></div><div className="result-dimensions">{[['E','I'],['S','N'],['T','F'],['J','P']].map(([a,b])=>{const total=scores[a as keyof typeof scores]+scores[b as keyof typeof scores],left=Math.round(scores[a as keyof typeof scores]/Math.max(1,total)*100);return <div key={a}><header><b>{a} {left}%</b><span>{b} {100-left}%</span></header><i><em style={{width:`${left}%`}}/></i></div>})}</div><div className="result-grid"><article><Compass/><h3>你的关系优势</h3>{report.strengths.map(x=><p key={x}><Check/>{x}</p>)}</article><article><Heart/><h3>更舒服的关系</h3><p>{report.relationship}</p></article><article><Sparkles/><h3>成长提醒</h3><p>{report.growth}</p></article></div><div className="result-note"><b>组合分析说明</b><p>推荐系统会综合你的 {result} 倾向、价值观“{(answers.values as string[]).slice(0,3).join('、')}”、生活节奏与理想对象要求。MBTI只作为沟通偏好线索，不会单独决定谁适合你。</p></div><footer><button className="secondary" onClick={()=>setPage(0)}><RotateCcw/>重新查看题目</button><button className="primary" onClick={onSaved}>用画像更新匹配<ArrowRight/></button></footer></section>}
 </motion.div>
}
