import { useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Check, Download, LoaderCircle, ShieldAlert, Trash2 } from 'lucide-react'
import { deleteMyAccount, exportMyData } from '../lib/account'
import { supabase } from '../lib/supabase'
export default function DataRights({session}:{session:Session}){
 const[confirm,setConfirm]=useState(''),[action,setAction]=useState<'export'|'delete'|null>(null),[message,setMessage]=useState(''),[error,setError]=useState('')
 const download=async()=>{if(action)return;setAction('export');setError('');try{const data=await exportMyData(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`tongpin-data-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('数据导出已开始下载')}catch(e){setError(e instanceof Error?e.message:'导出失败')}finally{setAction(null)}}
 const remove=async()=>{if(confirm!=='永久注销'||action)return;if(!window.confirm('这是最后一次确认：注销后所有账号数据不可恢复，确定继续吗？'))return;setAction('delete');setError('');try{await deleteMyAccount();await supabase?.auth.signOut();location.assign(new URL('./',location.href).href)}catch(e){setError(e instanceof Error?e.message:'注销失败');setAction(null)}}
 return <div className="data-rights">{message&&<div className="verify-message success"><Check/>{message}</div>}{error&&<div className="verify-message error">{error}</div>}<section><Download/><div><h2>导出我的数据</h2><p>下载个人资料、偏好、动态、评论、配对和自己发送的消息。</p><button className="secondary" disabled={Boolean(action)} onClick={()=>void download()}>{action==='export'?<LoaderCircle className="spin"/>:<Download/>}导出 JSON</button></div></section><section className="danger-zone"><ShieldAlert/><div><h2>永久注销账号</h2><p>此操作不可撤销。个人资料、动态、评论、消息和配对会被删除。</p><label>输入“永久注销”确认<input disabled={Boolean(action)} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button disabled={confirm!=='永久注销'||Boolean(action)} onClick={()=>void remove()}><Trash2/>{action==='delete'?<LoaderCircle className="spin"/>:'永久注销'}</button></div></section><small>当前账户：{session.user.email}</small></div>
}
