import { useMemo, useState } from 'react'
import { Crosshair, Heart, LocateFixed, LockKeyhole, MapPin, Navigation, SlidersHorizontal, Sparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import type { MatchPerson } from '../lib/profiles'

type Props={people:MatchPerson[];located:boolean;locating:boolean;radius:number;onRadius:(value:number)=>void;onLocate:()=>void;onOpen:(person:MatchPerson)=>void;onHeart:(person:MatchPerson)=>void}
export default function DiscoveryMap({people,located,locating,radius,onRadius,onLocate,onOpen,onHeart}:Props){
 const[selected,setSelected]=useState<string|undefined>(people[0]?.id)
 const shown=useMemo(()=>people.slice(0,8),[people]),active=shown.find(x=>x.id===selected)??shown[0]
 return <section className={`discovery-hero ${!shown.length?'discovery-empty':''}`}>
  <div className="discovery-copy"><span className="eyebrow"><Sparkles/>LIVE DISCOVERY</span><h2>看见你与附近的人，<br/><em>如何彼此靠近。</em></h2><p>距离告诉你们相隔多远，契合度呈现价值观、兴趣与生活节奏的共振。</p><div className="discovery-actions"><button className="primary" disabled={locating} onClick={onLocate}><LocateFixed/>{locating?'正在定位…':located?'更新我的位置':'开启附近发现'}</button><span><LockKeyhole/>仅保存约 1 公里精度的模糊位置</span></div><div className="discovery-stats"><div><b>{active?`${active.score}%`:'—'}</b><span>最高契合</span></div><div><b>{active?.distanceKm??'—'}{active&&<small> km</small>}</b><span>最近距离</span></div><div><b>{shown.length}</b><span>当前候选</span></div></div></div>
  <div className="connection-map" role="img" aria-label="附近用户距离和契合度关系图" aria-busy={locating}><div className="discovery-status" role="status" aria-live="polite">{locating?'正在更新附近发现…':located?`${shown.length} 位候选，点击头像查看详情`:'开启位置后查看附近候选'}</div>
   <div className="map-grid"/><div className="range-ring r1"/><div className="range-ring r2"/><div className="range-ring r3"/><span className="range-label l1">近</span><span className="range-label l2">{Math.round(radius/2)} km</span><span className="range-label l3">{radius} km</span>
   <motion.button className="map-me" aria-label="更新我的模糊位置" animate={{scale:[1,1.04,1]}} transition={{repeat:Infinity,duration:3}} disabled={locating} onClick={onLocate}><span className="map-self-avatar">你</span><i/><span>我的位置</span></motion.button>
   {shown.map((person,index)=>{const angle=((person.bearing??index*52)-90)*Math.PI/180,distance=Math.min(.94,Math.max(.25,(person.distanceKm??(index+1)*5)/radius)),x=50+Math.cos(angle)*distance*42,y=50+Math.sin(angle)*distance*42;return <motion.button key={person.id} className={`map-person ${active?.id===person.id?'active':''}`} style={{left:`${x}%`,top:`${y}%`}} initial={{opacity:0,scale:.4}} animate={{opacity:1,scale:1}} transition={{delay:index*.08}} onClick={()=>setSelected(person.id)} aria-pressed={active?.id===person.id} aria-label={`选择${person.name}，距离${person.distance}，契合度${person.score}%`}><img src={person.avatar} alt="" loading="lazy" decoding="async"/><b>{person.score}%</b><span>{person.distance}</span></motion.button>})}
   {!located&&<button className="map-permission" onClick={onLocate}><Navigation/><b>开启位置，点亮附近的人</b><span>我们不会展示你的精确坐标</span></button>}
   {active&&<motion.div className="map-person-card" key={active.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><img src={active.avatar} alt="" loading="lazy" decoding="async"/><div><b>{active.name} · {active.age}</b><span><MapPin/>{active.distance} · {active.score}% 契合</span></div><button onClick={()=>onOpen(active)}>查看</button><button className="map-heart" onClick={()=>onHeart(active)}><Heart/></button></motion.div>}
  </div>
  <div className="radius-control"><SlidersHorizontal aria-hidden="true"/><div className="radius-presets" aria-label="快速选择发现半径">{[5,20,50,100].map(value=><button type="button" className={radius===value?'active':''} onClick={()=>onRadius(value)} aria-pressed={radius===value} key={value}>{value}km</button>)}</div><label htmlFor="discovery-radius">发现半径 <b>{radius} km</b><input id="discovery-radius" type="range" min="5" max="100" step="5" value={radius} aria-valuetext={`${radius} 公里`} onChange={e=>onRadius(Number(e.target.value))}/></label><button aria-label="使用当前位置重新定位" disabled={locating} onClick={onLocate}><Crosshair/>{locating?'定位中':'重新定位'}</button></div>
 </section>
}
