import { useMemo, useState } from 'react'
import { Check, Heart, LoaderCircle, MessageCircle, RefreshCw, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import type { MatchPerson } from '../lib/profiles'
import { saveMatchFeedback, saveMatchWeights } from '../lib/assessment'
import { useDialogLifecycle } from '../hooks/useDialogLifecycle'
type Props={person:MatchPerson&{analysis?:Record<string,number>;topics?:string[]};onClose:()=>void;onChanged:()=>void}
const dimensions=[['values','价值观'],['lifestyle','生活节奏'],['interests','共同兴趣'],['communication','沟通方式'],['intent','关系方向']] as const
const initial={values:35,lifestyle:25,interests:20,communication:10,intent:10}
export default function MatchInsights({person,onClose,onChanged}:Props){
 const dialog=useDialogLifecycle<HTMLDivElement>(onClose)
 const[weights,setWeights]=useState(initial),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(true)
 const analysis=person.analysis??{values:person.dimensions[0],lifestyle:person.dimensions[2],interests:person.dimensions[1],communication:person.score,intent:person.score}
 const total=useMemo(()=>Object.values(weights).reduce((a,b)=>a+b,0),[weights])
 const adjust=(key:keyof typeof weights,value:number)=>{const others=Object.keys(weights).filter(x=>x!==key)as(keyof typeof weights)[],old=others.reduce((sum,x)=>sum+weights[x],0),rest=100-value;const next={...weights,[key]:value};let assigned=0;others.forEach((x,index)=>{const amount=index===others.length-1?rest-assigned:Math.round(weights[x]/old*rest);next[x]=amount;assigned+=amount});setWeights(next);setSaved(false)}
 const run=async(work:()=>Promise<void>,success:string)=>{if(saving)return;setSaving(true);setError('');try{await work();setFeedback(success);onChanged()}catch(e){setError(e instanceof Error?e.message:'操作失败，请稍后重试')}finally{setSaving(false)}}
 const choose=(type:'interested'|'not_now'|'not_fit')=>void run(()=>saveMatchFeedback(person.userId,type),type==='interested'?'已加入心动候选':type==='not_fit'?'已减少类似推荐':'已暂时跳过')
 const save=()=>void run(async()=>{if(total!==100)throw new Error('总权重必须为 100%');await saveMatchWeights(weights);setSaved(true)},'匹配重点已保存')
 return <div className="insight-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={dialog} tabIndex={-1} className="insight-modal" role="dialog" aria-modal="true" aria-label={`${person.name} 的匹配分析`}><header><div><span className="section-kicker"><Sparkles/>MATCH INTELLIGENCE</span><h2>{person.name} 的匹配分析</h2></div><button aria-label="关闭匹配分析" onClick={onClose}><X/></button></header><div className="insight-score"><div className="score-ring"><b>{person.score}</b><span>%</span></div><div><h3>你们有不错的同频基础</h3><p>分数来自你的评测、理想对象需求和双方公开资料。</p></div></div><div className="dimension-chart">{dimensions.map(([key,label])=><div key={key}><div><span>{label}</span><b>{analysis[key]??50}%</b></div><i><em style={{width:`${analysis[key]??50}%`}}/></i></div>)}</div><div className="insight-topics"><h3><MessageCircle/>可以这样开始聊天</h3>{(person.topics?.length?person.topics:['最近有什么事情让你觉得很有能量？','如果有一个完全自由的周末，你会怎么安排？']).map(x=><span key={x}>{x}</span>)}</div><details className="weight-editor"><summary><SlidersHorizontal/>调整匹配重点</summary><p>总权重必须是 100%，你的调整会影响之后的推荐顺序。</p>{dimensions.map(([key,label])=><label key={key}><span>{label}<b>{weights[key]}%</b></span><input disabled={saving} type="range" min="0" max="70" value={weights[key]} onChange={e=>adjust(key,Number(e.target.value))}/></label>)}<div className={`weight-total ${total===100?'valid':''}`}>总计 {total}%</div><button className="secondary" disabled={saving||saved||total!==100} onClick={save}>{saving?<LoaderCircle className="spin"/>:<RefreshCw/>}{saved?'已保存':'保存并更新推荐'}</button></details>{feedback&&<div className="insight-feedback"><Check/>{feedback}</div>}{error&&<div className="verify-message error">{error}</div>}<footer><button disabled={saving} onClick={()=>choose('not_fit')}><X/>不太合适</button><button disabled={saving} onClick={()=>choose('not_now')}><RefreshCw/>暂时略过</button><button className="primary" disabled={saving} onClick={()=>choose('interested')}>{saving?<LoaderCircle className="spin"/>:<Heart/>}感兴趣</button></footer></div></div>
}
