import { useCallback, useEffect, useState } from 'react'
import { Bell, BellRing, Check, LoaderCircle, RefreshCw, X } from 'lucide-react'
import { browserNotificationPermission, enableBrowserNotifications, fetchNotifications, markAllRead } from '../lib/notifications'

type Item = Awaited<ReturnType<typeof fetchNotifications>>[number]
export default function NotificationPanel({userId,onClose}:{userId:string;onClose:()=>void}){
 const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[permission,setPermission]=useState(browserNotificationPermission)
 const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await fetchNotifications(userId))}catch(e){setError(e instanceof Error?e.message:'通知加载失败')}finally{setLoading(false)}},[userId])
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load])
 const enable=async()=>{if(busy)return;setBusy(true);setError('');try{const result=await enableBrowserNotifications();setPermission(result);setMessage('浏览器通知已开启')}catch(e){setError(e instanceof Error?e.message:'开启失败')}finally{setBusy(false)}}
 const readAll=async()=>{if(busy||!items.some(x=>!x.read_at))return;setBusy(true);setError('');try{await markAllRead(userId);setItems(list=>list.map(x=>({...x,read_at:x.read_at??new Date().toISOString()})));setMessage('所有通知已标记为已读')}catch(e){setError(e instanceof Error?e.message:'标记失败')}finally{setBusy(false)}}
 return <aside className="notification-panel" aria-label="通知中心"><header><div><Bell/><h2>通知中心</h2></div><button aria-label="关闭通知中心" onClick={onClose}><X/></button></header><button className="browser-notify" disabled={busy||permission==='granted'||permission==='unsupported'} onClick={()=>void enable()}>{busy?<LoaderCircle className="spin"/>:<BellRing/>}{permission==='granted'?'浏览器通知已开启':permission==='unsupported'?'当前环境不支持通知':'开启浏览器通知'}</button>{message&&<p className="notify-message success">{message}</p>}{error&&<div className="notify-message error">{error}<button onClick={()=>void load()}><RefreshCw/>重试</button></div>}<button className="mark-read" disabled={busy||!items.some(x=>!x.read_at)} onClick={()=>void readAll()}><Check/>全部已读</button><div className="notification-items" aria-live="polite">{loading?<LoaderCircle className="spin"/>:!items.length?<div className="notify-empty"><Bell/><b>暂时没有通知</b><p>心动、消息与审核进度会出现在这里。</p></div>:items.map(item=><article className={item.read_at?'':'unread'} key={item.id}><i/><div><b>{item.title}</b><p>{item.body}</p><time>{new Date(item.created_at).toLocaleString()}</time></div></article>)}</div></aside>
}
