-- Self assessment, ideal partner requirements and explainable compatibility scoring.
alter table public.profiles add column if not exists assessment_completed boolean not null default false,add column if not exists self_assessment jsonb not null default '{}'::jsonb;
alter table public.preferences add column if not exists ideal_requirements jsonb not null default '{}'::jsonb,add column if not exists requirement_weights jsonb not null default '{"values":35,"lifestyle":25,"interests":20,"communication":10,"intent":10}'::jsonb;
create table public.compatibility_snapshots(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id)on delete cascade,target_user_id uuid not null references public.profiles(id)on delete cascade,overall_score integer not null check(overall_score between 0 and 100),dimensions jsonb not null default '{}'::jsonb,reasons text[] not null default '{}',created_at timestamptz not null default now(),unique(user_id,target_user_id));alter table public.compatibility_snapshots enable row level security;create policy "Users read own compatibility"on public.compatibility_snapshots for select to authenticated using(user_id=auth.uid());
create or replace function public.save_self_assessment(answers jsonb,requirements jsonb,weights jsonb default null)returns void language plpgsql security definer set search_path=''as $$begin if not public.can_interact(auth.uid())then raise exception'Account is not eligible to interact';end if;if jsonb_typeof(answers)<>'object'or jsonb_typeof(requirements)<>'object'then raise exception'Invalid assessment';end if;update public.profiles set self_assessment=answers,assessment_completed=true,updated_at=now()where id=auth.uid();update public.preferences set ideal_requirements=requirements,requirement_weights=coalesce(weights,requirement_weights),updated_at=now()where user_id=auth.uid();end;$$;grant execute on function public.save_self_assessment(jsonb,jsonb,jsonb)to authenticated;
create or replace function public.get_intelligent_matches(result_limit integer default 30)returns table(user_id uuid,nickname text,avatar_url text,school text,major text,birth_year smallint,personality text,bio text,interests text[],verified boolean,overall_score integer,value_score integer,lifestyle_score integer,interest_score integer,communication_score integer,intent_score integer,reasons text[],analysis jsonb)language sql stable security definer set search_path=''as $$
with me as(select p.*,pr.ideal_requirements,pr.requirement_weights,pr.relationship_intent from public.profiles p join public.preferences pr on pr.user_id=p.id where p.id=auth.uid()), candidates as(select p,me,
 least(100,50+coalesce((select count(*)from jsonb_object_keys(me.ideal_requirements)k where coalesce(p.relationship_values,'{}')&&array[k]),0)*8)::int val,
 least(100,45+coalesce((select count(*)from unnest(p.interests)i where i=any(coalesce((select array_agg(value)from jsonb_array_elements_text(coalesce(me.ideal_requirements->'interests','[]'::jsonb))), '{}'::text[]))),0)*12)::int interest,
 least(100,48+coalesce((select count(*)from unnest(p.lifestyle)i where i=any(coalesce((select array_agg(value)from jsonb_array_elements_text(coalesce(me.ideal_requirements->'lifestyle','[]'::jsonb))), '{}'::text[]))),0)*12)::int life,
 case when p.personality=me.ideal_requirements->>'personality' then 92 else 62 end::int communication,
 case when p.relationship_values && coalesce((select array_agg(value)from jsonb_array_elements_text(coalesce(me.ideal_requirements->'values','[]'::jsonb))), '{}'::text[]) then 88 else 64 end::int intent
 from public.profiles p cross join me where p.id<>me.id and p.profile_visible and p.onboarding_complete and p.assessment_completed and p.account_status='active')
select (c.p).id,(c.p).nickname,(c.p).avatar_url,(c.p).school,(c.p).major,(c.p).birth_year,(c.p).personality,(c.p).bio,(c.p).interests,(c.p).verified,
 round((c.val*.35+c.life*.25+c.interest*.20+c.communication*.10+c.intent*.10))::int,c.val,c.life,c.interest,c.communication,c.intent,
 array_remove(array[case when c.val>=75 then'关系价值观更接近'end,case when c.life>=70 then'生活节奏更容易相处'end,case when c.interest>=70 then'拥有可共同探索的兴趣'end,case when c.communication>=80 then'沟通方式可能更顺畅'end,case when c.intent>=80 then'关系期待方向一致'end],null),jsonb_build_object('values',c.val,'lifestyle',c.life,'interests',c.interest,'communication',c.communication,'intent',c.intent)
from candidates c order by 11 desc,(c.p).created_at desc limit greatest(1,least(result_limit,50));$$;grant execute on function public.get_intelligent_matches(integer)to authenticated;
