-- Anonymous matching concurrency, mutual reveal and reporting patch.
create or replace function public.join_anonymous_queue(chosen_mode text default'balanced')returns table(state text,session_id uuid)language plpgsql security definer set search_path=''as $$declare me uuid:=auth.uid();partner uuid;sid uuid;begin
 if not public.can_interact(me)then raise exception'Account is not eligible to interact';end if;
 select id into sid from public.anonymous_sessions where status='active'and me in(user_a,user_b)limit 1;
 if sid is not null then return query select'matched'::text,sid;return;end if;
 select q.user_id into partner from public.anonymous_queue q where q.user_id<>me and q.mode=chosen_mode and not exists(select 1 from public.blocks b where(b.blocker_id=me and b.blocked_id=q.user_id)or(b.blocker_id=q.user_id and b.blocked_id=me))order by q.joined_at for update skip locked limit 1;
 if partner is null then insert into public.anonymous_queue(user_id,mode,joined_at)values(me,chosen_mode,now())on conflict(user_id)do update set mode=excluded.mode,joined_at=now();return query select'waiting'::text,null::uuid;return;end if;
 delete from public.anonymous_queue where user_id in(me,partner);insert into public.anonymous_sessions(user_a,user_b)values(least(me,partner),greatest(me,partner))returning id into sid;insert into public.anonymous_messages(session_id,sender_id,kind,content)values(sid,me,'system','你们已匿名相遇。先聊聊彼此，而不是标签。');return query select'matched'::text,sid;
end;$$;
create or replace function public.get_revealed_partner(target_session uuid)returns table(id uuid,nickname text,avatar_url text,life_stage text,city text,verified boolean)language sql stable security definer set search_path=''as $$select p.id,p.nickname,p.avatar_url,p.life_stage,p.city,p.verified from public.anonymous_sessions s join public.profiles p on p.id=case when s.user_a=auth.uid()then s.user_b else s.user_a end where s.id=target_session and auth.uid()in(s.user_a,s.user_b)and s.reveal_a and s.reveal_b$$;grant execute on function public.get_revealed_partner(uuid)to authenticated;
create or replace function public.report_anonymous_session(target_session uuid,report_reason text)returns void language plpgsql security definer set search_path=''as $$declare partner uuid;begin select case when user_a=auth.uid()then user_b else user_a end into partner from public.anonymous_sessions where id=target_session and auth.uid()in(user_a,user_b);if partner is null then raise exception'Session unavailable';end if;insert into public.reports(reporter_id,target_user_id,reason,details)values(auth.uid(),partner,report_reason,'匿名会话 '||target_session::text);update public.anonymous_sessions set status='ended',ended_at=now()where id=target_session;end;$$;grant execute on function public.report_anonymous_session(uuid,text)to authenticated;
