-- Commercial foundation: invitations, membership entitlements, orders, support and consented funnel events.
create table if not exists public.waitlist_entries(id uuid primary key default gen_random_uuid(),email text not null,city text,school text,referral_code text,consent boolean not null default false,status text not null default 'waiting' check(status in('waiting','invited','joined','declined')),created_at timestamptz not null default now());
create unique index if not exists waitlist_email_unique on public.waitlist_entries(lower(email));
create table if not exists public.invitation_codes(code text primary key,created_by uuid references auth.users(id) on delete set null,max_uses int not null default 1 check(max_uses between 1 and 1000),uses int not null default 0,expires_at timestamptz,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.membership_plans(id text primary key,name text not null,description text not null,price_cents int not null check(price_cents>=0),billing_period text not null check(billing_period in('month','quarter','year','one_time')),entitlements jsonb not null default '{}'::jsonb,active boolean not null default true,sort_order int not null default 0,created_at timestamptz not null default now());
create table if not exists public.subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,plan_id text not null references public.membership_plans(id),status text not null check(status in('trialing','active','past_due','cancelled','expired')),starts_at timestamptz not null default now(),ends_at timestamptz not null,auto_renew boolean not null default false,provider text,provider_subscription_id text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists subscriptions_user_status on public.subscriptions(user_id,status,ends_at desc);
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,plan_id text references public.membership_plans(id),amount_cents int not null check(amount_cents>=0),currency text not null default 'CNY',status text not null check(status in('pending','paid','failed','cancelled','refunded')),provider text,provider_order_id text,idempotency_key uuid not null default gen_random_uuid(),created_at timestamptz not null default now(),paid_at timestamptz,unique(user_id,idempotency_key));
create table if not exists public.support_tickets(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,category text not null check(category in('account','safety','verification','payment','membership','privacy','other')),subject text not null check(char_length(subject) between 3 and 120),body text not null check(char_length(body) between 10 and 3000),status text not null default 'open' check(status in('open','in_progress','resolved','closed')),priority text not null default 'normal' check(priority in('normal','high','urgent')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.product_events(id bigint generated always as identity primary key,user_id uuid references auth.users(id) on delete set null,event_name text not null,event_properties jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
insert into public.membership_plans(id,name,description,price_cents,billing_period,entitlements,sort_order) values
('free','基础版','开始真实连接所需的基础能力',0,'month','{"daily_likes":5,"daily_recommendations":10,"advanced_filters":false,"see_admirers":false,"match_report":false,"rewinds":0}'::jsonb,0),
('plus','同频 Plus','更主动地发现契合对象',2900,'month','{"daily_likes":30,"daily_recommendations":50,"advanced_filters":true,"see_admirers":true,"match_report":true,"rewinds":3}'::jsonb,10),
('plus_quarter','同频 Plus 季度版','适合持续认真了解彼此',6900,'quarter','{"daily_likes":30,"daily_recommendations":50,"advanced_filters":true,"see_admirers":true,"match_report":true,"rewinds":12}'::jsonb,20)
on conflict(id) do update set name=excluded.name,description=excluded.description,price_cents=excluded.price_cents,entitlements=excluded.entitlements,sort_order=excluded.sort_order;
alter table public.waitlist_entries enable row level security;alter table public.invitation_codes enable row level security;alter table public.membership_plans enable row level security;alter table public.subscriptions enable row level security;alter table public.orders enable row level security;alter table public.support_tickets enable row level security;alter table public.product_events enable row level security;
create policy plans_public_read on public.membership_plans for select using(active);
create policy own_subscriptions_read on public.subscriptions for select to authenticated using(user_id=auth.uid());
create policy own_orders_read on public.orders for select to authenticated using(user_id=auth.uid());
create policy own_tickets_read on public.support_tickets for select to authenticated using(user_id=auth.uid() or public.is_admin());
create policy own_tickets_insert on public.support_tickets for insert to authenticated with check(user_id=auth.uid());
create policy admin_tickets_update on public.support_tickets for update to authenticated using(public.is_admin()) with check(public.is_admin());
create or replace function public.join_waitlist(contact_email text,contact_city text default null,contact_school text default null,referral text default null,accepted boolean default false) returns void language plpgsql security definer set search_path='' as $f$ begin if not accepted then raise exception 'Consent is required';end if;if contact_email!~*'^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Invalid email';end if;insert into public.waitlist_entries(email,city,school,referral_code,consent) values(lower(trim(contact_email)),nullif(trim(contact_city),''),nullif(trim(contact_school),''),nullif(trim(referral),''),true) on conflict((lower(email))) do update set city=excluded.city,school=excluded.school,referral_code=excluded.referral_code,consent=true;end;$f$;
grant execute on function public.join_waitlist(text,text,text,text,boolean) to anon,authenticated;
create or replace function public.get_my_membership() returns jsonb language sql stable security definer set search_path='' as $f$ select jsonb_build_object('plan',coalesce((select to_jsonb(p) from public.subscriptions s join public.membership_plans p on p.id=s.plan_id where s.user_id=auth.uid() and s.status in('trialing','active') and s.ends_at>now() order by s.ends_at desc limit 1),(select to_jsonb(p) from public.membership_plans p where p.id='free')),'subscription',(select to_jsonb(s) from public.subscriptions s where s.user_id=auth.uid() and s.status in('trialing','active') and s.ends_at>now() order by s.ends_at desc limit 1),'orders',coalesce((select jsonb_agg(to_jsonb(o) order by o.created_at desc) from (select * from public.orders where user_id=auth.uid() order by created_at desc limit 20)o),'[]'::jsonb));$f$;
grant execute on function public.get_my_membership() to authenticated;
create or replace function public.get_my_admirers() returns table(user_id uuid,nickname text,avatar_url text,school text,created_at timestamptz,can_view boolean) language sql stable security definer set search_path='' as $f$ with premium as(select exists(select 1 from public.subscriptions s where s.user_id=auth.uid() and s.status in('trialing','active') and s.ends_at>now()) ok) select h.sender_id,case when premium.ok then p.nickname else '有人对你心动' end,case when premium.ok then p.avatar_url else null end,case when premium.ok then p.school else '开通 Plus 后查看' end,h.created_at,premium.ok from public.heart_signals h cross join premium join public.profiles p on p.id=h.sender_id where h.receiver_id=auth.uid() and not exists(select 1 from public.user_blocks b where(b.blocker_id=auth.uid() and b.blocked_id=h.sender_id)or(b.blocker_id=h.sender_id and b.blocked_id=auth.uid())) order by h.created_at desc limit 50;$f$;
grant execute on function public.get_my_admirers() to authenticated;
create or replace function public.create_pending_order(chosen_plan text) returns uuid language plpgsql security definer set search_path='' as $f$ declare target public.membership_plans;created uuid;begin select * into target from public.membership_plans where id=chosen_plan and active and price_cents>0;if not found then raise exception 'Plan is unavailable';end if;insert into public.orders(user_id,plan_id,amount_cents,status) values(auth.uid(),target.id,target.price_cents,'pending') returning id into created;return created;end;$f$;
grant execute on function public.create_pending_order(text) to authenticated;
create or replace function public.track_product_event(chosen_event text,properties jsonb default '{}'::jsonb) returns void language plpgsql security definer set search_path='' as $f$ begin if chosen_event not in('membership_viewed','plan_selected','admirers_viewed','support_created','waitlist_joined') then raise exception 'Unsupported event';end if;insert into public.product_events(user_id,event_name,event_properties) values(auth.uid(),chosen_event,coalesce(properties,'{}'::jsonb));end;$f$;
grant execute on function public.track_product_event(text,jsonb) to authenticated;
revoke all on public.waitlist_entries,public.invitation_codes,public.subscriptions,public.orders,public.product_events from anon,authenticated;
grant select on public.membership_plans to anon,authenticated;grant select on public.subscriptions,public.orders to authenticated;grant select,insert on public.support_tickets to authenticated;
