-- Anonymous random matching, safe chat and compatibility games.
create table public.anonymous_queue(user_id uuid primary key references public.profiles(id)on delete cascade,mode text not null default'balanced'check(mode in('balanced','values','adventure')),joined_at timestamptz not null default now());
create table public.anonymous_sessions(id uuid primary key default gen_random_uuid(),user_a uuid not null references public.profiles(id)on delete cascade,user_b uuid not null references public.profiles(id)on delete cascade,status text not null default'active'check(status in('active','ended','revealed')),reveal_a boolean not null default false,reveal_b boolean not null default false,compatibility_score integer not null default 50 check(compatibility_score between 0 and 100),created_at timestamptz not null default now(),ended_at timestamptz,check(user_a<user_b));
create unique index anonymous_one_active_a on public.anonymous_sessions(user_a)where status='active';create unique index anonymous_one_active_b on public.anonymous_sessions(user_b)where status='active';
create table public.anonymous_messages(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.anonymous_sessions(id)on delete cascade,sender_id uuid not null references public.profiles(id)on delete cascade,kind text not null default'text'check(kind in('text','system','game')),content text not null check(char_length(content)between 1 and 2000),created_at timestamptz not null default now());create index anonymous_messages_idx on public.anonymous_messages(session_id,created_at);
create table public.anonymous_games(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.anonymous_sessions(id)on delete cascade,game_type text not null check(game_type in('sync','scenario')),prompt text not null,options jsonb not null,answers jsonb not null default'{}',result_score integer,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
alter table public.anonymous_queue enable row level security;alter table public.anonymous_sessions enable row level security;alter table public.anonymous_messages enable row level security;alter table public.anonymous_games enable row level security;
create policy "Users read own queue"on public.anonymous_queue for select to authenticated using(user_id=auth.uid());
create policy "Participants read anonymous sessions"on public.anonymous_sessions for select to authenticated using(auth.uid()in(user_a,user_b));
create policy "Participants read anonymous messages"on public.anonymous_messages for select to authenticated using(exists(select 1 from public.anonymous_sessions s where s.id=session_id and auth.uid()in(s.user_a,s.user_b)));
create policy "Participants send anonymous messages"on public.anonymous_messages for insert to authenticated with check(sender_id=auth.uid()and public.can_interact(auth.uid())and exists(select 1 from public.anonymous_sessions s where s.id=session_id and s.status='active'and auth.uid()in(s.user_a,s.user_b)));
create policy "Participants read anonymous games"on public.anonymous_games for select to authenticated using(exists(select 1 from public.anonymous_sessions s where s.id=session_id and auth.uid()in(s.user_a,s.user_b)));

do $$begin alter publication supabase_realtime add table public.anonymous_messages;exception when duplicate_object then null;end$$;

create or replace function public.join_anonymous_queue(chosen_mode text default'balanced')returns table(state text,session_id uuid)language plpgsql security definer set search_path=''as $$declare me uuid:=auth.uid();partner uuid;sid uuid;begin
 if not public.can_interact(me)then raise exception'Account is not eligible to interact';end if;
 select q.user_id into partner from public.anonymous_queue q where q.user_id<>me and q.mode=chosen_mode and not exists(select 1 from public.blocks b where(b.blocker_id=me and b.blocked_id=q.user_id)or(b.blocker_id=q.user_id and b.blocked_id=me))order by q.joined_at for update skip locked limit 1;
 if partner is null then insert into public.anonymous_queue(user_id,mode,joined_at)values(me,chosen_mode,now())on conflict(user_id)do update set mode=excluded.mode,joined_at=now();return query select'waiting'::text,null::uuid;return;end if;
 delete from public.anonymous_queue where user_id in(me,partner);insert into public.anonymous_sessions(user_a,user_b)values(least(me,partner),greatest(me,partner))returning id into sid;insert into public.anonymous_messages(session_id,sender_id,kind,content)values(sid,me,'system','你们已匿名相遇。先聊聊彼此，而不是标签。');return query select'matched'::text,sid;
end;$$;grant execute on function public.join_anonymous_queue(text)to authenticated;
create or replace function public.get_anonymous_session()returns setof public.anonymous_sessions language sql stable security definer set search_path=''as $$select*from public.anonymous_sessions where status='active'and auth.uid()in(user_a,user_b)order by created_at desc limit 1$$;grant execute on function public.get_anonymous_session()to authenticated;
create or replace function public.leave_anonymous_chat(target_session uuid)returns void language plpgsql security definer set search_path=''as $$begin delete from public.anonymous_queue where user_id=auth.uid();update public.anonymous_sessions set status='ended',ended_at=now()where id=target_session and auth.uid()in(user_a,user_b);end;$$;grant execute on function public.leave_anonymous_chat(uuid)to authenticated;
create or replace function public.request_anonymous_reveal(target_session uuid)returns boolean language plpgsql security definer set search_path=''as $$declare both_ready boolean;begin update public.anonymous_sessions set reveal_a=case when user_a=auth.uid()then true else reveal_a end,reveal_b=case when user_b=auth.uid()then true else reveal_b end where id=target_session and status='active'and auth.uid()in(user_a,user_b);select reveal_a and reveal_b into both_ready from public.anonymous_sessions where id=target_session;if both_ready then update public.anonymous_sessions set status='revealed'where id=target_session;end if;return coalesce(both_ready,false);end;$$;grant execute on function public.request_anonymous_reveal(uuid)to authenticated;
create or replace function public.create_anonymous_game(target_session uuid,chosen_type text)returns uuid language plpgsql security definer set search_path=''as $$declare gid uuid;question text;choices jsonb;begin if not exists(select 1 from public.anonymous_sessions where id=target_session and status='active'and auth.uid()in(user_a,user_b))then raise exception'Active session required';end if;if chosen_type='scenario'then question:='旅行途中突然下起大雨，你更希望两个人怎么做？';choices:='["马上改变计划，找一家小店聊天","撑伞继续走，意外也是旅程的一部分","各自提议，然后一起决定"]';else question:='理想的周末，你更接近哪一种状态？';choices:='["提前规划好每个安排","睡醒再决定，保持自由","一半计划，一半留白"]';end if;insert into public.anonymous_games(session_id,game_type,prompt,options,created_by)values(target_session,chosen_type,question,choices,auth.uid())returning id into gid;return gid;end;$$;grant execute on function public.create_anonymous_game(uuid,text)to authenticated;
create or replace function public.answer_anonymous_game(game_id uuid,choice integer)returns integer language plpgsql security definer set search_path=''as $$declare answers_now jsonb;score integer;sid uuid;begin select session_id,answers into sid,answers_now from public.anonymous_games where id=game_id and exists(select 1 from public.anonymous_sessions s where s.id=session_id and s.status='active'and auth.uid()in(s.user_a,s.user_b))for update;if sid is null then raise exception'Game unavailable';end if;answers_now:=answers_now||jsonb_build_object(auth.uid()::text,choice);if jsonb_object_length(answers_now)>=2 then select case when count(distinct value)=1 then 100 else 68 end into score from jsonb_each_text(answers_now);end if;update public.anonymous_games set answers=answers_now,result_score=score where id=game_id;if score is not null then update public.anonymous_sessions set compatibility_score=round((compatibility_score+score)/2.0)where id=sid;end if;return score;end;$$;grant execute on function public.answer_anonymous_game(uuid,integer)to authenticated;
