-- Launch readiness: legal consent, moderation, notifications and enforcement.
alter table public.profiles add column if not exists birth_date date,add column if not exists accepted_terms_at timestamptz,add column if not exists accepted_privacy_at timestamptz,add column if not exists account_status text not null default 'active' check(account_status in('active','muted','suspended','banned')),add column if not exists muted_until timestamptz,add constraint adult_birth_date check(birth_date is null or birth_date<=current_date-interval '18 years');
alter table public.posts add column if not exists moderation_status text not null default 'published' check(moderation_status in('published','hidden','removed'));
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id)on delete cascade,type text not null,title text not null,body text not null,link text,read_at timestamptz,created_at timestamptz not null default now());
create index notifications_user_idx on public.notifications(user_id,created_at desc);alter table public.notifications enable row level security;create policy "Users read own notifications"on public.notifications for select to authenticated using(auth.uid()=user_id);create policy "Users update own notifications"on public.notifications for update to authenticated using(auth.uid()=user_id)with check(auth.uid()=user_id);
create table public.moderation_actions(id uuid primary key default gen_random_uuid(),admin_id uuid not null references public.profiles(id),target_user_id uuid references public.profiles(id),target_post_id uuid references public.posts(id),action text not null check(action in('warn','mute','suspend','ban','hide_post','remove_post','resolve_report')),reason text not null,expires_at timestamptz,created_at timestamptz not null default now(),check(target_user_id is not null or target_post_id is not null));alter table public.moderation_actions enable row level security;create policy "Admins manage moderation actions"on public.moderation_actions for all to authenticated using(public.is_admin())with check(public.is_admin());
create or replace function public.can_interact(uid uuid)returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.profiles where id=uid and account_status='active'and(muted_until is null or muted_until<now())and(birth_date is not null and birth_date<=current_date-interval'18 years')and accepted_terms_at is not null and accepted_privacy_at is not null)$$;
create or replace function public.accept_legal(birthday date)returns void language plpgsql security definer set search_path=''as $$begin if birthday>current_date-interval'18 years'then raise exception'You must be 18 or older';end if;update public.profiles set birth_date=birthday,birth_year=extract(year from birthday)::int,accepted_terms_at=now(),accepted_privacy_at=now()where id=auth.uid();end;$$;grant execute on function public.accept_legal(date)to authenticated;
create or replace function public.moderate_target(target_user uuid,target_post uuid,chosen_action text,action_reason text,duration_hours integer default null)returns void language plpgsql security definer set search_path=''as $$begin if not public.is_admin()then raise exception'Admin required';end if;insert into public.moderation_actions(admin_id,target_user_id,target_post_id,action,reason,expires_at)values(auth.uid(),target_user,target_post,chosen_action,action_reason,case when duration_hours is null then null else now()+make_interval(hours=>duration_hours)end);if chosen_action='mute'then update public.profiles set muted_until=now()+make_interval(hours=>coalesce(duration_hours,24))where id=target_user;elsif chosen_action in('suspend','ban')then update public.profiles set account_status=case when chosen_action='ban'then'banned'else'suspended'end where id=target_user;elsif chosen_action in('hide_post','remove_post')then update public.posts set moderation_status=case when chosen_action='hide_post'then'hidden'else'removed'end where id=target_post;end if;end;$$;grant execute on function public.moderate_target(uuid,uuid,text,text,integer)to authenticated;
create or replace function public.resolve_report(report_id uuid,resolution text)returns void language plpgsql security definer set search_path=''as $$begin if not public.is_admin()then raise exception'Admin required';end if;update public.reports set status=resolution where id=report_id and resolution in('resolved','dismissed');end;$$;grant execute on function public.resolve_report(uuid,text)to authenticated;
create or replace function public.notify_user(target uuid,event_type text,event_title text,event_body text,event_link text default null)returns void language plpgsql security definer set search_path=''as $$begin if auth.uid() is null then raise exception'Authentication required';end if;insert into public.notifications(user_id,type,title,body,link)values(target,event_type,event_title,event_body,event_link);end;$$;grant execute on function public.notify_user(uuid,text,text,text,text)to authenticated;
drop policy if exists "Authenticated users read posts"on public.posts;create policy "Authenticated users read published posts"on public.posts for select to authenticated using(moderation_status='published'or author_id=auth.uid()or public.is_admin());
